spring.application.name=forgeAI

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.ai.vectorstore.simple.path=./data/vector_store.json

spring.datasource.url=jdbc:h2:file:./data/forgeai;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
